"""
FraudTrap — Monitoring Package
"""

from monitoring.drift import (
    compute_psi,
    compute_kl_divergence,
    compute_feature_drift,
    compute_all_feature_drift,
    compute_embedding_drift,
    compute_concept_drift,
    detect_feature_outliers,
    DEFAULT_MONITORED_FEATURES,
    DriftResult,
    EmbeddingDriftResult,
    ConceptDriftResult,
)

from monitoring.metrics_collector import (
    get_clickhouse_client,
    init_clickhouse_tables,
    fetch_recent_scores,
    fetch_recent_labels,
    fetch_recent_embeddings,
    compute_daily_metrics,
    persist_daily_metrics,
    persist_drift_metrics,
    persist_embedding_drift,
    persist_concept_drift,
    run_daily_rollup,
    DailyModelMetrics,
)

from monitoring.alerts import (
    AlertManager,
    Alert,
    AlertSeverity,
    AlertCategory,
    get_alert_manager,
    fire_sla_breach,
    fire_drift_spike,
    fire_concept_drift,
    fire_performance_drop,
    fire_data_quality,
    fire_scoring_errors,
    fire_model_reload,
    DEFAULT_RUNBOOKS,
)

from monitoring.chaos import (
    ChaosRunner,
    ChaosExperiment,
    ChaosResult,
    ChaosType,
    ChaosSeverity,
    ChaosScenario,
    run_chaos_experiment,
    run_chaos_scenario,
    CHAOS_EXPERIMENTS,
    CHAOS_SCENARIOS,
)

from scoring.experiments import (
    ExperimentManager,
    ExperimentConfig,
    ExperimentVariant,
    ExperimentStatus,
    VariantType,
    ExperimentResult,
    ExperimentRouter,
    create_experiment,
    route_experiment,
    record_experiment_outcome,
)

__all__ = [
    # Drift
    "compute_psi",
    "compute_kl_divergence",
    "compute_feature_drift",
    "compute_all_feature_drift",
    "compute_embedding_drift",
    "compute_concept_drift",
    "detect_feature_outliers",
    "DEFAULT_MONITORED_FEATURES",
    "DriftResult",
    "EmbeddingDriftResult",
    "ConceptDriftResult",
    # Metrics
    "get_clickhouse_client",
    "init_clickhouse_tables",
    "fetch_recent_scores",
    "fetch_recent_labels",
    "fetch_recent_embeddings",
    "compute_daily_metrics",
    "persist_daily_metrics",
    "persist_drift_metrics",
    "persist_embedding_drift",
    "persist_concept_drift",
    "run_daily_rollup",
    "DailyModelMetrics",
    # Alerts
    "AlertManager",
    "Alert",
    "AlertSeverity",
    "AlertCategory",
    "get_alert_manager",
    "fire_sla_breach",
    "fire_drift_spike",
    "fire_concept_drift",
    "fire_performance_drop",
    "fire_data_quality",
    "fire_scoring_errors",
    "fire_model_reload",
    "DEFAULT_RUNBOOKS",
    # Experiments (A/B Testing)
    "ExperimentManager",
    "ExperimentConfig",
    "ExperimentVariant",
    "ExperimentStatus",
    "VariantType",
    "ExperimentResult",
    "ExperimentRouter",
    "create_experiment",
    "route_experiment",
    "record_experiment_outcome",
    # Chaos Testing
    "ChaosRunner",
    "ChaosExperiment",
    "ChaosResult",
    "ChaosType",
    "ChaosSeverity",
    "ChaosScenario",
    "run_chaos_experiment",
    "run_chaos_scenario",
    "CHAOS_EXPERIMENTS",
    "CHAOS_SCENARIOS",
]
